### ISSUE TITLE
Bug when run npm run dev

### ISSUE THREAD

**Issue by tpvt99** [Plortinus/vue-multiple-pages#18]
(function (exports, require, module, __filename, __dirname) { const { join, resolve } = require('path')
                                                                                                           ^

SyntaxError: Unexpected token {
at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at requireConfig (/home/web/newProject/node_modules/webpack/bin/convert-argv.js:96:18)
    at /home/web/newProject/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)

Can you help me solve this problem. Otherwise , I see this architecture is greate

**Comment by Plortinus** [comment]
Try to update your `nodejs` version
