### ISSUE TITLE
Adding module error

### ISSUE THREAD

**Issue by Gargo** [Plortinus/vue-multiple-pages#74]
You wrote as title:
`A multiple Pages Starter use Vue-cli3`

https://vuetifyjs.com/ru/getting-started/quick-start
```
$vue add vuetify

📦  Installing vue-cli-plugin-vuetify...

+ vue-cli-plugin-vuetify@0.1.6
added 1 package from 1 contributor and audited 12412 packages in 49.243s
found 0 vulnerabilities


✔  Successfully installed plugin: vue-cli-plugin-vuetify

? Use a pre-made template? (will replace App.vue and HelloWorld.vue) No
? Use custom theme? No
? Use a-la-carte components? No
? Use babel/polyfill? No

🚀  Invoking generator for vue-cli-plugin-vuetify...
📦  Installing additional dependencies...
added 1 package from 1 contributor and audited 12413 packages in 21.405s
found 0 vulnerabilities

-  Running completion hooks... ERROR  Error: ENOENT: no such file or directory, open 'F:\git_repos\vue-multiple-pages\src\main.js'
Error: ENOENT: no such file or directory, open 'F:\git_repos\vue-multiple-pages\src\main.js'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at Object.updateMain (F:\git_repos\vue-multiple-pages\node_modules\vue-cli-plugin-vuetify\generator\helpers.js:48:24)
    at api.onCreateComplete (F:\git_repos\vue-multiple-pages\node_modules\vue-cli-plugin-vuetify\generator\index.js:74:13)
    at runGenerator (C:\Users\Admin\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:136:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

So how to add new modules to this project if vue-cli requires `main.js` which doesn't exist.

**Comment by Plortinus** [comment]
[refer to this guide](https://vuetifyjs.com/ru/getting-started/quick-start#existing-applications)
first:
```js
$ npm install vuetify --save
# or
$ yarn add vuetify
```
then in every `app.js`
```js
import Vue from 'vue'
import Vuetify from 'vuetify'
 
Vue.use(Vuetify)
```
